security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            id: App\Security\UserProvider
    # SS notes:
    # This is a case statement. The first one that matches is the one that is chosen
    # keys that activate authentication systems go here
    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            # SS: give a guest badge if not recognized - they are considered anonymous - let authentication happen later
            lazy: true # Don't check security until we run a security check. Symfony 4.4 feature
            provider: app_user_provider # more about how the firewall should behave
            guard:
                authenticators:
                    - App\Security\SimpleSSOAuthenticator
            # SS: guard is a subcomponent that helps end users make auth listeners easily
            # SS: You can have as many authenticators as you want

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        # SS: Currently we set everyone to have this role
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY } # This whitelists urls. The role is something everyone has no matter what
        - { path: '^/lucky/number', roles: ROLE_USER } # Loss of role stops things dead in its track
        - { path: '^/', roles: ROLE_USER } # Login is now required for login route. This requires logged in status for all routes
        # SS: Ensure the most specific is at the top because first match will be used
